### ISSUE TITLE
Small mistake in the documentation

### ISSUE THREAD

**Issue by tivvit** [aerospike/aerospike-tools-backup#2]
http://www.aerospike.com/docs/tools/backup/asrestore.html

this example:
`$ asrestore --host 1.2.3.4 --directory backup_2015_08_24 --namespace test,prod`

should be:
`$ asrestore --host 1.2.3.4 --directory backup_2015_08_24 --namespace test prod`

**Comment by tivvit** [comment]
so I'm sorry, it is not like I said, but the namespace change  throws 
`restore failed due to wrong namespace name`

Maybe the problem is in that on target aerospike I have same namespace as on source (test in example)

**Comment by wchu-citrusleaf** [comment]
correct. destination namespace is only needed when restoring into a namespace different than the source.

**Comment by tivvit** [comment]
But I wanted to restore it to different namespace. When this assumption is correct `--namespace source_ns, dest_ns` it does not work correctly. Talking about version `3.5.11`.

**Comment by wchu-citrusleaf** [comment]
Can you elaborate what happens when using <code>--namespace source_ns, dest_ns</code> ?
Any warning on the server side?

**Comment by citrusraj** [comment]
works like

--namespace ns1,ns2 

No spaces.
