### ISSUE TITLE
How can I deserialize the list bins?

### ISSUE THREAD

**Issue by revington** [aerospike/aerospike-tools-backup#4]
I want to use to use this tool to generate a backup, but also I want to be able to process that backup file in order to build a secondary index in a different database. I know I can perform an scan, but for my particular problem, processing the file might be more interesting.

**Comment by wchu-citrusleaf** [comment]
list/map data in Aerospike are msgpacked data. 

if you want to decode it, you can use the unpacker -
https://github.com/aerospike/aerospike-common/blob/master/src/main/aerospike/as_msgpack_serializer.c
